// AUTO-GENERATED by scripts/sync-docs.mjs — do not edit by hand.
// Static import registry for vendored docs (mirrors the runbooks loader).

export type DocImporter = () => Promise<{ default: React.ComponentType }>;

export const DOC_IMPORTERS: Record<string, DocImporter> = {
  "adr/README": () => import("@/content/docs/adr/README.md"),
  "adr/architecture-decisions": () => import("@/content/docs/adr/architecture-decisions.md"),
  "architecture/consensus-and-block-production": () => import("@/content/docs/architecture/consensus-and-block-production.md"),
  "architecture": () => import("@/content/docs/architecture/index.md"),
  "faq": () => import("@/content/docs/faq.md"),
  "fno-guides": () => import("@/content/docs/fno-guides/index.md"),
  "fno-guides/mainnet/cardano-availability": () => import("@/content/docs/fno-guides/mainnet/cardano-availability.md"),
  "fno-guides/mainnet": () => import("@/content/docs/fno-guides/mainnet/index.md"),
  "fno-guides/mainnet/install-node-and-keys": () => import("@/content/docs/fno-guides/mainnet/install-node-and-keys.md"),
  "fno-guides/mainnet/requirements": () => import("@/content/docs/fno-guides/mainnet/requirements.md"),
  "fno-guides/mainnet/run-validator": () => import("@/content/docs/fno-guides/mainnet/run-validator.md"),
  "fno-guides/mainnet/wireguard-integration": () => import("@/content/docs/fno-guides/mainnet/wireguard-integration.md"),
  "fno-guides/preprod/cardano-availability": () => import("@/content/docs/fno-guides/preprod/cardano-availability.md"),
  "fno-guides/preprod": () => import("@/content/docs/fno-guides/preprod/index.md"),
  "fno-guides/preprod/install-node-and-keys": () => import("@/content/docs/fno-guides/preprod/install-node-and-keys.md"),
  "fno-guides/preprod/requirements": () => import("@/content/docs/fno-guides/preprod/requirements.md"),
  "fno-guides/preprod/run-validator": () => import("@/content/docs/fno-guides/preprod/run-validator.md"),
  "fno-guides/preprod/wireguard-integration": () => import("@/content/docs/fno-guides/preprod/wireguard-integration.md"),
  "fno-guides/preprod-wireguard-onboarding": () => import("@/content/docs/fno-guides/preprod-wireguard-onboarding.md"),
  "": () => import("@/content/docs/index.md"),
  "processes/change-management": () => import("@/content/docs/processes/change-management.md"),
};
